name: Build Check

on:
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      update: ${{ steps.check.outputs.changed }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install Packages
        run: npm ci

      - name: Build Files
        run: npm run build
